---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: epilayer-ssd
provisioner: csi.epilayer.eu
parameters:
  type: ssd
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
mountOptions:
  - discard

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: epilayer-hdd
provisioner: csi.epilayer.eu
parameters:
  type: hdd
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
mountOptions:
  - discard
